// ----------------------------------------------------------------------------------------------------
// This code is generated based on *.dsl file.
// Do not edit this file. Edit *.dls files instead.
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Ziggurat.Contracts.Definition
{
	[Serializable, DataContract]
	public sealed partial class CreateNewProject : ICommand
	{
		[DataMember(Order = 0 )] public Guid Id { get; set; }
		[DataMember(Order = 1 )] public string Name { get; set; }
		[DataMember(Order = 2 )] public string ShortName { get; set; }

		public CreateNewProject() { }
		public CreateNewProject(Guid id, string name, string shortName)
		{
			Id = id;
			Name = name;
			ShortName = shortName;
		}

	}

	[Serializable, DataContract]
	public sealed partial class ProjectCreationFailed : IEvent
	{
		[DataMember(Order = 0 )] public Guid ProjectId { get; set; }
		[DataMember(Order = 1 )] public string Name { get; set; }
		[DataMember(Order = 2 )] public string ShortName { get; set; }
		[DataMember(Order = 3 )] public IList<string> Errors { get; set; }

		public ProjectCreationFailed() { }
		public ProjectCreationFailed(Guid projectId, string name, string shortName, IList<string> errors)
		{
			ProjectId = projectId;
			Name = name;
			ShortName = shortName;
			Errors = errors;
		}

	}

	[Serializable, DataContract]
	public sealed partial class NewProjectRegistered : IEvent
	{
		[DataMember(Order = 0 )] public Guid ProjectId { get; set; }
		[DataMember(Order = 1 )] public string Name { get; set; }
		[DataMember(Order = 2 )] public string ShortName { get; set; }

		public NewProjectRegistered() { }
		public NewProjectRegistered(Guid projectId, string name, string shortName)
		{
			ProjectId = projectId;
			Name = name;
			ShortName = shortName;
		}

	}

	[Serializable, DataContract]
	public sealed partial class CreateLayoutForProject : ICommand
	{
		[DataMember(Order = 0 )] public Guid ProjectId { get; set; }
		[DataMember(Order = 1 )] public Guid ProjectLayoutId { get; set; }

		public CreateLayoutForProject() { }
		public CreateLayoutForProject(Guid projectId, Guid projectLayoutId)
		{
			ProjectId = projectId;
			ProjectLayoutId = projectLayoutId;
		}

	}

	[Serializable, DataContract]
	public sealed partial class ProjectLayoutCreated : IEvent
	{
		[DataMember(Order = 0 )] public Guid ProjectId { get; set; }
		[DataMember(Order = 1 )] public Guid ProjectLayoutId { get; set; }

		public ProjectLayoutCreated() { }
		public ProjectLayoutCreated(Guid projectId, Guid projectLayoutId)
		{
			ProjectId = projectId;
			ProjectLayoutId = projectLayoutId;
		}

	}

	[Serializable, DataContract]
	public sealed partial class AssignProjectLayoutToProject : ICommand
	{
		[DataMember(Order = 0 )] public Guid ProjectId { get; set; }
		[DataMember(Order = 1 )] public Guid ProjectLayoutId { get; set; }

		public AssignProjectLayoutToProject() { }
		public AssignProjectLayoutToProject(Guid projectId, Guid projectLayoutId)
		{
			ProjectId = projectId;
			ProjectLayoutId = projectLayoutId;
		}

	}

	[Serializable, DataContract]
	public sealed partial class ProjectLayoutAssignedToProject : IEvent
	{
		[DataMember(Order = 0 )] public Guid ProjectId { get; set; }
		[DataMember(Order = 1 )] public Guid ProjectLayoutId { get; set; }

		public ProjectLayoutAssignedToProject() { }
		public ProjectLayoutAssignedToProject(Guid projectId, Guid projectLayoutId)
		{
			ProjectId = projectId;
			ProjectLayoutId = projectLayoutId;
		}

	}

	[Serializable, DataContract]
	public sealed partial class ProjectCreated : IEvent
	{
		[DataMember(Order = 0 )] public Guid Id { get; set; }
		[DataMember(Order = 1 )] public Guid ProjectLayoutId { get; set; }
		[DataMember(Order = 2 )] public string Name { get; set; }
		[DataMember(Order = 3 )] public string ShortName { get; set; }

		public ProjectCreated() { }
		public ProjectCreated(Guid id, Guid projectLayoutId, string name, string shortName)
		{
			Id = id;
			ProjectLayoutId = projectLayoutId;
			Name = name;
			ShortName = shortName;
		}

	}

	[Serializable, DataContract]
	public sealed partial class CreateForm : ICommand
	{
		[DataMember(Order = 0 )] public Guid ProjectId { get; set; }
		[DataMember(Order = 1 )] public Guid FormId { get; set; }
		[DataMember(Order = 2 )] public string Name { get; set; }
		[DataMember(Order = 3 )] public string UniqueName { get; set; }

		public CreateForm() { }
		public CreateForm(Guid projectId, Guid formId, string name, string uniqueName)
		{
			ProjectId = projectId;
			FormId = formId;
			Name = name;
			UniqueName = uniqueName;
		}

	}

	[Serializable, DataContract]
	public sealed partial class FormCreated : IEvent
	{
		[DataMember(Order = 0 )] public Guid ProjectId { get; set; }
		[DataMember(Order = 1 )] public Guid FormId { get; set; }
		[DataMember(Order = 2 )] public string Name { get; set; }
		[DataMember(Order = 3 )] public string UniqueName { get; set; }

		public FormCreated() { }
		public FormCreated(Guid projectId, Guid formId, string name, string uniqueName)
		{
			ProjectId = projectId;
			FormId = formId;
			Name = name;
			UniqueName = uniqueName;
		}

	}

	[Serializable, DataContract]
	public sealed partial class AttachFormToProjectLayout : ICommand
	{
		[DataMember(Order = 0 )] public Guid ProjectLayoutId { get; set; }
		[DataMember(Order = 1 )] public Guid FormId { get; set; }
		[DataMember(Order = 2 )] public Guid ProjectId { get; set; }

		public AttachFormToProjectLayout() { }
		public AttachFormToProjectLayout(Guid projectLayoutId, Guid formId, Guid projectId)
		{
			ProjectLayoutId = projectLayoutId;
			FormId = formId;
			ProjectId = projectId;
		}

	}

	[Serializable, DataContract]
	public sealed partial class FormAttachedToProjectLayout : IEvent
	{
		[DataMember(Order = 0 )] public Guid ProjectLayoutId { get; set; }
		[DataMember(Order = 1 )] public Guid FormId { get; set; }
		[DataMember(Order = 2 )] public Guid ProjectId { get; set; }

		public FormAttachedToProjectLayout() { }
		public FormAttachedToProjectLayout(Guid projectLayoutId, Guid formId, Guid projectId)
		{
			ProjectLayoutId = projectLayoutId;
			FormId = formId;
			ProjectId = projectId;
		}

	}

	[Serializable, DataContract]
	public sealed partial class MoveFormInProjectLayout : ICommand
	{
		[DataMember(Order = 0 )] public Guid ProjectLayoutId { get; set; }
		[DataMember(Order = 1 )] public Guid FormId { get; set; }
		[DataMember(Order = 2 )] public string BlockHeader { get; set; }
		[DataMember(Order = 3 )] public int Order { get; set; }

		public MoveFormInProjectLayout() { }
		public MoveFormInProjectLayout(Guid projectLayoutId, Guid formId, string blockHeader, int order)
		{
			ProjectLayoutId = projectLayoutId;
			FormId = formId;
			BlockHeader = blockHeader;
			Order = order;
		}

	}

	[Serializable, DataContract]
	public sealed partial class FormMovedInProjectLayout : IEvent
	{
		[DataMember(Order = 0 )] public Guid ProjectLayoutId { get; set; }
		[DataMember(Order = 1 )] public Guid FormId { get; set; }
		[DataMember(Order = 2 )] public string BlockHeader { get; set; }
		[DataMember(Order = 3 )] public int Order { get; set; }

		public FormMovedInProjectLayout() { }
		public FormMovedInProjectLayout(Guid projectLayoutId, Guid formId, string blockHeader, int order)
		{
			ProjectLayoutId = projectLayoutId;
			FormId = formId;
			BlockHeader = blockHeader;
			Order = order;
		}

	}

	[Serializable, DataContract]
	public sealed partial class AddNewPropertyToForm : ICommand
	{
		[DataMember(Order = 0 )] public Guid FormId { get; set; }
		[DataMember(Order = 1 )] public Guid PropertyId { get; set; }
		[DataMember(Order = 2 )] public PropertyType Type { get; set; }
		[DataMember(Order = 3 )] public string Name { get; set; }

		public AddNewPropertyToForm() { }
		public AddNewPropertyToForm(Guid formId, Guid propertyId, PropertyType type, string name)
		{
			FormId = formId;
			PropertyId = propertyId;
			Type = type;
			Name = name;
		}

	}

	[Serializable, DataContract]
	public sealed partial class NewPropertyAddedToForm : IEvent
	{
		[DataMember(Order = 0 )] public Guid FormId { get; set; }
		[DataMember(Order = 1 )] public Guid PropertyId { get; set; }
		[DataMember(Order = 2 )] public PropertyType Type { get; set; }
		[DataMember(Order = 3 )] public string Name { get; set; }

		public NewPropertyAddedToForm() { }
		public NewPropertyAddedToForm(Guid formId, Guid propertyId, PropertyType type, string name)
		{
			FormId = formId;
			PropertyId = propertyId;
			Type = type;
			Name = name;
		}

	}

	[Serializable, DataContract]
	public sealed partial class SetFormulaForConcatenationProperty : ICommand
	{
		[DataMember(Order = 0 )] public Guid FormId { get; set; }
		[DataMember(Order = 1 )] public Guid PropertyId { get; set; }
		[DataMember(Order = 2 )] public ConcatenationFormulaDescriptor Formula { get; set; }

		public SetFormulaForConcatenationProperty() { }
		public SetFormulaForConcatenationProperty(Guid formId, Guid propertyId, ConcatenationFormulaDescriptor formula)
		{
			FormId = formId;
			PropertyId = propertyId;
			Formula = formula;
		}

	}

	[Serializable, DataContract]
	public sealed partial class ConcatenationPropertyFormulaSet : IPropertyDefinitionEvent
	{
		[DataMember(Order = 0 )] public Guid FormId { get; set; }
		[DataMember(Order = 1 )] public Guid PropertyId { get; set; }
		[DataMember(Order = 2 )] public ConcatenationFormulaDescriptor Formula { get; set; }

		public ConcatenationPropertyFormulaSet() { }
		public ConcatenationPropertyFormulaSet(Guid formId, Guid propertyId, ConcatenationFormulaDescriptor formula)
		{
			FormId = formId;
			PropertyId = propertyId;
			Formula = formula;
		}

	}

	[Serializable, DataContract]
	public sealed partial class MakePropertyUnused : ICommand
	{
		[DataMember(Order = 0 )] public Guid FormId { get; set; }
		[DataMember(Order = 1 )] public Guid PropertyId { get; set; }

		public MakePropertyUnused() { }
		public MakePropertyUnused(Guid formId, Guid propertyId)
		{
			FormId = formId;
			PropertyId = propertyId;
		}

	}

	[Serializable, DataContract]
	public sealed partial class MakePropertyUsed : ICommand
	{
		[DataMember(Order = 0 )] public Guid FormId { get; set; }
		[DataMember(Order = 1 )] public Guid PropertyId { get; set; }

		public MakePropertyUsed() { }
		public MakePropertyUsed(Guid formId, Guid propertyId)
		{
			FormId = formId;
			PropertyId = propertyId;
		}

	}

	[Serializable, DataContract]
	public sealed partial class PropertyMadeUnused : IPropertyDefinitionEvent
	{
		[DataMember(Order = 0 )] public Guid FormId { get; set; }
		[DataMember(Order = 1 )] public Guid PropertyId { get; set; }

		public PropertyMadeUnused() { }
		public PropertyMadeUnused(Guid formId, Guid propertyId)
		{
			FormId = formId;
			PropertyId = propertyId;
		}

	}

	[Serializable, DataContract]
	public sealed partial class PropertyMadeUsed : IPropertyDefinitionEvent
	{
		[DataMember(Order = 0 )] public Guid FormId { get; set; }
		[DataMember(Order = 1 )] public Guid PropertyId { get; set; }

		public PropertyMadeUsed() { }
		public PropertyMadeUsed(Guid formId, Guid propertyId)
		{
			FormId = formId;
			PropertyId = propertyId;
		}

	}

}

